-- MySQL Script generated by MySQL Workbench
-- Thu Sep  9 15:31:27 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema smartcommerci
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema smartcommerci
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `smartcommerci` DEFAULT CHARACTER SET latin1 ;
USE `smartcommerci` ;

-- -----------------------------------------------------
-- Table `smartcommerci`.`master`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartcommerci`.`master` (
  `master_id` INT(11) NOT NULL AUTO_INCREMENT,
  `master_business_name` TEXT NULL DEFAULT NULL,
  `master_business_cnpj` TEXT NULL DEFAULT NULL,
  `master_business_razao` TEXT NULL DEFAULT NULL,
  `master_business_telefone` TEXT NULL DEFAULT NULL,
  `master_business_mail` TEXT NULL DEFAULT NULL,
  `master_business_horario` TEXT NULL DEFAULT NULL,
  `master_business_endereco` TEXT NULL DEFAULT NULL,
  `master_business_numero` TEXT NULL DEFAULT NULL,
  `master_business_cep` TEXT NULL DEFAULT NULL,
  `master_business_cidade` TEXT NULL DEFAULT NULL,
  `master_business_estado` TEXT NULL DEFAULT NULL,
  `master_custom_segmento` TEXT NULL DEFAULT NULL,
  `master_custom_logo` TEXT NULL DEFAULT NULL,
  `master_custom_cor_primeira` TEXT NULL DEFAULT NULL,
  `master_custom_cor_segunda` TEXT NULL DEFAULT NULL,
  `master_custom_cor_terceira` TEXT NULL DEFAULT NULL,
  `master_custom_cor_quarta` TEXT NULL DEFAULT NULL,
  `master_custom_categorias` TEXT NULL DEFAULT NULL,
  `master_custom_ferramentas` TEXT NULL DEFAULT NULL,
  `master_updatedaAt` DATETIME NULL DEFAULT NULL,
  `master_createdAt` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`master_id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `smartcommerci`.`affiliates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartcommerci`.`affiliates` (
  `affiliates_id` INT(11) NOT NULL AUTO_INCREMENT,
  `affiliates_master_id` INT(11) NOT NULL,
  `affiliates_business_name` TEXT NULL DEFAULT NULL,
  `affiliates_business_telefone` TEXT NULL DEFAULT NULL,
  `affiliates_business_mail` TEXT NULL DEFAULT NULL,
  `affiliates_business_horario` TEXT NULL DEFAULT NULL,
  `affiliates_business_endereco` TEXT NULL DEFAULT NULL,
  `affiliates_business_numero` TEXT NULL DEFAULT NULL,
  `affiliates_business_cep` TEXT NULL DEFAULT NULL,
  `affiliates_business_cidade` TEXT NULL DEFAULT NULL,
  `affiliates_business_estado` TEXT NULL DEFAULT NULL,
  `affiliates_updatedaAt` DATETIME NULL DEFAULT NULL,
  `affiliates_createdAt` DATETIME NULL DEFAULT NULL,
  `master_master_id` INT(11) NOT NULL,
  PRIMARY KEY (`affiliates_id`, `master_master_id`),
  INDEX `fk_affiliates_master1_idx` (`master_master_id` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `smartcommerci`.`users_client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartcommerci`.`users_client` (
  `users_client_id` INT(11) NOT NULL AUTO_INCREMENT,
  `users_client_affiliate_id` INT(11) NOT NULL,
  `users_client_name` TEXT NULL DEFAULT NULL,
  `users_client_mail` TEXT NULL DEFAULT NULL,
  `users_client_token` TEXT NULL DEFAULT NULL,
  `users_client_cpf` TEXT NULL DEFAULT NULL,
  `users_client_endereco` TEXT NULL DEFAULT NULL,
  `users_client_cep` TEXT NULL DEFAULT NULL,
  `users_client_bairro` TEXT NULL DEFAULT NULL,
  `users_client_cidade` TEXT NULL DEFAULT NULL,
  `users_client_listas_compras` TEXT NULL DEFAULT NULL,
  `users_affiliate_updatedaAt` DATETIME NULL DEFAULT NULL,
  `users_affiliate_createdAt` DATETIME NULL DEFAULT NULL,
  `affiliates_affiliates_id` INT(11) NOT NULL,
  `affiliates_master_master_id` INT(11) NOT NULL,
  PRIMARY KEY (`users_client_id`, `affiliates_affiliates_id`, `affiliates_master_master_id`),
  INDEX `fk_users_client_affiliates1_idx` (`affiliates_affiliates_id` ASC, `affiliates_master_master_id` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `smartcommerci`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartcommerci`.`cart` (
  `cart_id` INT(11) NOT NULL AUTO_INCREMENT,
  `cart_affiliate_id` INT(11) NOT NULL,
  `cart_client_id` INT(11) NOT NULL,
  `cart_status` TEXT NULL DEFAULT NULL,
  `cart_conteudo` TEXT NULL DEFAULT NULL,
  `cart_valor_total` DECIMAL(10,0) NULL DEFAULT NULL,
  `cart_updatedaAt` DATETIME NULL DEFAULT NULL,
  `cart_createdAt` DATETIME NULL DEFAULT NULL,
  `affiliates_affiliates_id` INT(11) NOT NULL,
  `affiliates_master_master_id` INT(11) NOT NULL,
  `users_client_users_client_id` INT(11) NOT NULL,
  `users_client_affiliates_affiliates_id` INT(11) NOT NULL,
  `users_client_affiliates_master_master_id` INT(11) NOT NULL,
  PRIMARY KEY (`cart_id`, `affiliates_affiliates_id`, `affiliates_master_master_id`, `users_client_users_client_id`, `users_client_affiliates_affiliates_id`, `users_client_affiliates_master_master_id`),
  INDEX `fk_cart_affiliates1_idx` (`affiliates_affiliates_id` ASC, `affiliates_master_master_id` ASC) VISIBLE,
  INDEX `fk_cart_users_client1_idx` (`users_client_users_client_id` ASC, `users_client_affiliates_affiliates_id` ASC, `users_client_affiliates_master_master_id` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `smartcommerci`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartcommerci`.`orders` (
  `order_id` INT(11) NOT NULL AUTO_INCREMENT,
  `order_affiliate_id` INT(11) NOT NULL,
  `order_client_id` INT(11) NOT NULL,
  `order_status` TEXT NULL DEFAULT NULL,
  `order_data_entrega` DATETIME NULL DEFAULT NULL,
  `order_metodo_pagamento` TEXT NULL DEFAULT NULL,
  `order_cpf_nf` TEXT NULL DEFAULT NULL,
  `order_tamanho_cesta` TEXT NULL DEFAULT NULL,
  `order_conteudo` TEXT NULL DEFAULT NULL,
  `order_valor_total` DECIMAL(10,0) NULL DEFAULT NULL,
  `order_updatedaAt` DATETIME NULL DEFAULT NULL,
  `order_createdAt` DATETIME NULL DEFAULT NULL,
  `affiliates_affiliates_id` INT(11) NOT NULL,
  `affiliates_master_master_id` INT(11) NOT NULL,
  `users_client_users_client_id` INT(11) NOT NULL,
  `users_client_affiliates_affiliates_id` INT(11) NOT NULL,
  `users_client_affiliates_master_master_id` INT(11) NOT NULL,
  PRIMARY KEY (`order_id`, `affiliates_affiliates_id`, `affiliates_master_master_id`, `users_client_users_client_id`, `users_client_affiliates_affiliates_id`, `users_client_affiliates_master_master_id`),
  INDEX `fk_orders_affiliates1_idx` (`affiliates_affiliates_id` ASC, `affiliates_master_master_id` ASC) VISIBLE,
  INDEX `fk_orders_users_client1_idx` (`users_client_users_client_id` ASC, `users_client_affiliates_affiliates_id` ASC, `users_client_affiliates_master_master_id` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `smartcommerci`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartcommerci`.`posts` (
  `post_id` INT(11) NOT NULL AUTO_INCREMENT,
  `post_affiliate_id` INT(11) NOT NULL,
  `post_titulo` TEXT NULL DEFAULT NULL,
  `post_chamada` TEXT NULL DEFAULT NULL,
  `post_categoria` TEXT NULL DEFAULT NULL,
  `post_etiquetas` TEXT NULL DEFAULT NULL,
  `post_updatedaAt` DATETIME NULL DEFAULT NULL,
  `post_createdAt` DATETIME NULL DEFAULT NULL,
  `affiliates_affiliates_id` INT(11) NOT NULL,
  `affiliates_master_master_id` INT(11) NOT NULL,
  PRIMARY KEY (`post_id`, `affiliates_affiliates_id`, `affiliates_master_master_id`),
  INDEX `fk_posts_affiliates1_idx` (`affiliates_affiliates_id` ASC, `affiliates_master_master_id` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `smartcommerci`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartcommerci`.`products` (
  `product_id` INT(11) NOT NULL AUTO_INCREMENT,
  `product_affiliate_id` INT(11) NOT NULL,
  `product_descricao` TEXT NULL DEFAULT NULL,
  `product_valor` DECIMAL(10,0) NULL DEFAULT NULL,
  `product_categoria` TEXT NULL DEFAULT NULL,
  `product_fabricacao` TEXT NULL DEFAULT NULL,
  `product_estoque` INT(11) NULL DEFAULT NULL,
  `product_medida` TEXT NULL DEFAULT NULL,
  `product_etiquetas` TEXT NULL DEFAULT NULL,
  `product_updatedaAt` DATETIME NULL DEFAULT NULL,
  `product_createdAt` DATETIME NULL DEFAULT NULL,
  `affiliates_affiliates_id` INT(11) NOT NULL,
  `affiliates_master_master_id` INT(11) NOT NULL,
  PRIMARY KEY (`product_id`, `affiliates_affiliates_id`, `affiliates_master_master_id`),
  INDEX `fk_products_affiliates1_idx` (`affiliates_affiliates_id` ASC, `affiliates_master_master_id` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `smartcommerci`.`users_affiliate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartcommerci`.`users_affiliate` (
  `users_affiliate_id` INT(11) NOT NULL AUTO_INCREMENT,
  `users_affiliate_master_id` INT(11) NOT NULL,
  `users_affiliate_name` TEXT NULL DEFAULT NULL,
  `users_affiliate_perfil` TEXT NULL DEFAULT NULL,
  `users_affiliate_mail` TEXT NULL DEFAULT NULL,
  `users_affiliate_token` TEXT NULL DEFAULT NULL,
  `users_affiliate_updatedaAt` DATETIME NULL DEFAULT NULL,
  `users_affiliate_createdAt` DATETIME NULL DEFAULT NULL,
  `affiliates_affiliates_id` INT(11) NOT NULL,
  `affiliates_master_master_id` INT(11) NOT NULL,
  PRIMARY KEY (`users_affiliate_id`, `affiliates_affiliates_id`, `affiliates_master_master_id`),
  INDEX `fk_users_affiliate_affiliates1_idx` (`affiliates_affiliates_id` ASC, `affiliates_master_master_id` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `smartcommerci`.`users_master`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartcommerci`.`users_master` (
  `users_master_id` INT(11) NOT NULL AUTO_INCREMENT,
  `users_master_name` TEXT NULL DEFAULT NULL,
  `users_master_mail` TEXT NULL DEFAULT NULL,
  `users_master_token` TEXT NULL DEFAULT NULL,
  `users_master_updatedaAt` DATETIME NULL DEFAULT NULL,
  `users_master_createdAt` DATETIME NULL DEFAULT NULL,
  `users_affiliate_users_affiliate_id` INT(11) NOT NULL,
  `master_master_id` INT(11) NOT NULL,
  PRIMARY KEY (`users_master_id`, `users_affiliate_users_affiliate_id`, `master_master_id`),
  INDEX `fk_users_master_users_affiliate_idx` (`users_affiliate_users_affiliate_id` ASC) VISIBLE,
  INDEX `fk_users_master_master1_idx` (`master_master_id` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
